# # Python code to create a file
file = open('py.txt','w')
file.write("This is the write command")
file.write("It allows us to write in a particular file")
file.write("THis is a new text by dev sharma end = '\n'")
d = input("Enter ur message : ")
file.write()
file.close()
f = open('py.txt','r')
print(f.read())
